/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DealerRouteImport } from './routes/dealer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as DealerIndexRouteImport } from './routes/dealer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as StoreIndexRouteImport } from './routes/_store.index'
import { Route as DealerWalletRouteImport } from './routes/dealer.wallet'
import { Route as DealerQuotationsRouteImport } from './routes/dealer.quotations'
import { Route as DealerCatalogRouteImport } from './routes/dealer.catalog'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminTiersRouteImport } from './routes/admin.tiers'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSalesOrderRouteImport } from './routes/admin.sales-order'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminQuotationsRouteImport } from './routes/admin.quotations'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminDealersRouteImport } from './routes/admin.dealers'
import { Route as AdminCreditRouteImport } from './routes/admin.credit'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCatalogsRouteImport } from './routes/admin.catalogs'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountTaxInvoicesRouteImport } from './routes/account.tax-invoices'
import { Route as AccountQuotationsRouteImport } from './routes/account.quotations'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AccountAffiliateRouteImport } from './routes/account.affiliate'
import { Route as StoreTermsRouteImport } from './routes/_store.terms'
import { Route as StoreShopRouteImport } from './routes/_store.shop'
import { Route as StoreQuickOrderRouteImport } from './routes/_store.quick-order'
import { Route as StorePrivacyRouteImport } from './routes/_store.privacy'
import { Route as StoreErrorRouteImport } from './routes/_store.error'
import { Route as StoreCookiesRouteImport } from './routes/_store.cookies'
import { Route as StoreContactRouteImport } from './routes/_store.contact'
import { Route as StoreConfiguratorRouteImport } from './routes/_store.configurator'
import { Route as StoreCompareRouteImport } from './routes/_store.compare'
import { Route as StoreCheckoutRouteImport } from './routes/_store.checkout'
import { Route as StoreCatalogsRouteImport } from './routes/_store.catalogs'
import { Route as StoreCartRouteImport } from './routes/_store.cart'
import { Route as StoreAboutRouteImport } from './routes/_store.about'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as StoreCatalogsIndexRouteImport } from './routes/_store.catalogs.index'
import { Route as ApiV1WalletTopupSlipRouteImport } from './routes/api/v1/wallet-topup-slip'
import { Route as ApiV1ProfileAvatarRouteImport } from './routes/api/v1/profile-avatar'
import { Route as ApiV1ProductsRouteImport } from './routes/api/v1/products'
import { Route as ApiV1PaymentSlipRouteImport } from './routes/api/v1/payment-slip'
import { Route as ApiV1HeroBannerRouteImport } from './routes/api/v1/hero-banner'
import { Route as ApiV1CustomerDocumentRouteImport } from './routes/api/v1/customer-document'
import { Route as ApiV1CatalogAssetRouteImport } from './routes/api/v1/catalog-asset'
import { Route as ApiV1AdminTaxInvoiceRouteImport } from './routes/api/v1/admin-tax-invoice'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AdminQuotationsQuotationIdRouteImport } from './routes/admin.quotations.$quotationId'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AdminMembersUserIdRouteImport } from './routes/admin.members.$userId'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'
import { Route as StoreProductsSlugRouteImport } from './routes/_store.products.$slug'
import { Route as StoreDealerRegisterRouteImport } from './routes/_store.dealer.register'
import { Route as StoreCatalogsIdRouteImport } from './routes/_store.catalogs.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerRoute = DealerRouteImport.update({
  id: '/dealer',
  path: '/dealer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerIndexRoute = DealerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DealerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const DealerWalletRoute = DealerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DealerRoute,
} as any)
const DealerQuotationsRoute = DealerQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => DealerRoute,
} as any)
const DealerCatalogRoute = DealerCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => DealerRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTiersRoute = AdminTiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesOrderRoute = AdminSalesOrderRouteImport.update({
  id: '/sales-order',
  path: '/sales-order',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotationsRoute = AdminQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealersRoute = AdminDealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditRoute = AdminCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogsRoute = AdminCatalogsRouteImport.update({
  id: '/catalogs',
  path: '/catalogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountTaxInvoicesRoute = AccountTaxInvoicesRouteImport.update({
  id: '/tax-invoices',
  path: '/tax-invoices',
  getParentRoute: () => AccountRoute,
} as any)
const AccountQuotationsRoute = AccountQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAffiliateRoute = AccountAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AccountRoute,
} as any)
const StoreTermsRoute = StoreTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => StoreRoute,
} as any)
const StoreShopRoute = StoreShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StoreRoute,
} as any)
const StoreQuickOrderRoute = StoreQuickOrderRouteImport.update({
  id: '/quick-order',
  path: '/quick-order',
  getParentRoute: () => StoreRoute,
} as any)
const StorePrivacyRoute = StorePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => StoreRoute,
} as any)
const StoreErrorRoute = StoreErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCookiesRoute = StoreCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContactRoute = StoreContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => StoreRoute,
} as any)
const StoreConfiguratorRoute = StoreConfiguratorRouteImport.update({
  id: '/configurator',
  path: '/configurator',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCompareRoute = StoreCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCatalogsRoute = StoreCatalogsRouteImport.update({
  id: '/catalogs',
  path: '/catalogs',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAboutRoute = StoreAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => StoreRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const StoreCatalogsIndexRoute = StoreCatalogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreCatalogsRoute,
} as any)
const ApiV1WalletTopupSlipRoute = ApiV1WalletTopupSlipRouteImport.update({
  id: '/api/v1/wallet-topup-slip',
  path: '/api/v1/wallet-topup-slip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProfileAvatarRoute = ApiV1ProfileAvatarRouteImport.update({
  id: '/api/v1/profile-avatar',
  path: '/api/v1/profile-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProductsRoute = ApiV1ProductsRouteImport.update({
  id: '/api/v1/products',
  path: '/api/v1/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PaymentSlipRoute = ApiV1PaymentSlipRouteImport.update({
  id: '/api/v1/payment-slip',
  path: '/api/v1/payment-slip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HeroBannerRoute = ApiV1HeroBannerRouteImport.update({
  id: '/api/v1/hero-banner',
  path: '/api/v1/hero-banner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CustomerDocumentRoute = ApiV1CustomerDocumentRouteImport.update({
  id: '/api/v1/customer-document',
  path: '/api/v1/customer-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CatalogAssetRoute = ApiV1CatalogAssetRouteImport.update({
  id: '/api/v1/catalog-asset',
  path: '/api/v1/catalog-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminTaxInvoiceRoute = ApiV1AdminTaxInvoiceRouteImport.update({
  id: '/api/v1/admin-tax-invoice',
  path: '/api/v1/admin-tax-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuotationsQuotationIdRoute =
  AdminQuotationsQuotationIdRouteImport.update({
    id: '/$quotationId',
    path: '/$quotationId',
    getParentRoute: () => AdminQuotationsRoute,
  } as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminMembersUserIdRoute = AdminMembersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminMembersRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const StoreProductsSlugRoute = StoreProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreDealerRegisterRoute = StoreDealerRegisterRouteImport.update({
  id: '/dealer/register',
  path: '/dealer/register',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCatalogsIdRoute = StoreCatalogsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoreCatalogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dealer': typeof DealerRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof StoreAboutRoute
  '/cart': typeof StoreCartRoute
  '/catalogs': typeof StoreCatalogsRouteWithChildren
  '/checkout': typeof StoreCheckoutRoute
  '/compare': typeof StoreCompareRoute
  '/configurator': typeof StoreConfiguratorRoute
  '/contact': typeof StoreContactRoute
  '/cookies': typeof StoreCookiesRoute
  '/error': typeof StoreErrorRoute
  '/privacy': typeof StorePrivacyRoute
  '/quick-order': typeof StoreQuickOrderRoute
  '/shop': typeof StoreShopRoute
  '/terms': typeof StoreTermsRoute
  '/account/affiliate': typeof AccountAffiliateRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/quotations': typeof AccountQuotationsRoute
  '/account/tax-invoices': typeof AccountTaxInvoicesRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/catalogs': typeof AdminCatalogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/credit': typeof AdminCreditRoute
  '/admin/dealers': typeof AdminDealersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/quotations': typeof AdminQuotationsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales-order': typeof AdminSalesOrderRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tiers': typeof AdminTiersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dealer/catalog': typeof DealerCatalogRoute
  '/dealer/quotations': typeof DealerQuotationsRoute
  '/dealer/wallet': typeof DealerWalletRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dealer/': typeof DealerIndexRoute
  '/catalogs/$id': typeof StoreCatalogsIdRoute
  '/dealer/register': typeof StoreDealerRegisterRoute
  '/products/$slug': typeof StoreProductsSlugRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/members/$userId': typeof AdminMembersUserIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/quotations/$quotationId': typeof AdminQuotationsQuotationIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/v1/admin-tax-invoice': typeof ApiV1AdminTaxInvoiceRoute
  '/api/v1/catalog-asset': typeof ApiV1CatalogAssetRoute
  '/api/v1/customer-document': typeof ApiV1CustomerDocumentRoute
  '/api/v1/hero-banner': typeof ApiV1HeroBannerRoute
  '/api/v1/payment-slip': typeof ApiV1PaymentSlipRoute
  '/api/v1/products': typeof ApiV1ProductsRoute
  '/api/v1/profile-avatar': typeof ApiV1ProfileAvatarRoute
  '/api/v1/wallet-topup-slip': typeof ApiV1WalletTopupSlipRoute
  '/catalogs/': typeof StoreCatalogsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof StoreAboutRoute
  '/cart': typeof StoreCartRoute
  '/checkout': typeof StoreCheckoutRoute
  '/compare': typeof StoreCompareRoute
  '/configurator': typeof StoreConfiguratorRoute
  '/contact': typeof StoreContactRoute
  '/cookies': typeof StoreCookiesRoute
  '/error': typeof StoreErrorRoute
  '/privacy': typeof StorePrivacyRoute
  '/quick-order': typeof StoreQuickOrderRoute
  '/shop': typeof StoreShopRoute
  '/terms': typeof StoreTermsRoute
  '/account/affiliate': typeof AccountAffiliateRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/quotations': typeof AccountQuotationsRoute
  '/account/tax-invoices': typeof AccountTaxInvoicesRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/catalogs': typeof AdminCatalogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/credit': typeof AdminCreditRoute
  '/admin/dealers': typeof AdminDealersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/quotations': typeof AdminQuotationsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales-order': typeof AdminSalesOrderRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tiers': typeof AdminTiersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dealer/catalog': typeof DealerCatalogRoute
  '/dealer/quotations': typeof DealerQuotationsRoute
  '/dealer/wallet': typeof DealerWalletRoute
  '/': typeof StoreIndexRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/dealer': typeof DealerIndexRoute
  '/catalogs/$id': typeof StoreCatalogsIdRoute
  '/dealer/register': typeof StoreDealerRegisterRoute
  '/products/$slug': typeof StoreProductsSlugRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/members/$userId': typeof AdminMembersUserIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/quotations/$quotationId': typeof AdminQuotationsQuotationIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/v1/admin-tax-invoice': typeof ApiV1AdminTaxInvoiceRoute
  '/api/v1/catalog-asset': typeof ApiV1CatalogAssetRoute
  '/api/v1/customer-document': typeof ApiV1CustomerDocumentRoute
  '/api/v1/hero-banner': typeof ApiV1HeroBannerRoute
  '/api/v1/payment-slip': typeof ApiV1PaymentSlipRoute
  '/api/v1/products': typeof ApiV1ProductsRoute
  '/api/v1/profile-avatar': typeof ApiV1ProfileAvatarRoute
  '/api/v1/wallet-topup-slip': typeof ApiV1WalletTopupSlipRoute
  '/catalogs': typeof StoreCatalogsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dealer': typeof DealerRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_store/about': typeof StoreAboutRoute
  '/_store/cart': typeof StoreCartRoute
  '/_store/catalogs': typeof StoreCatalogsRouteWithChildren
  '/_store/checkout': typeof StoreCheckoutRoute
  '/_store/compare': typeof StoreCompareRoute
  '/_store/configurator': typeof StoreConfiguratorRoute
  '/_store/contact': typeof StoreContactRoute
  '/_store/cookies': typeof StoreCookiesRoute
  '/_store/error': typeof StoreErrorRoute
  '/_store/privacy': typeof StorePrivacyRoute
  '/_store/quick-order': typeof StoreQuickOrderRoute
  '/_store/shop': typeof StoreShopRoute
  '/_store/terms': typeof StoreTermsRoute
  '/account/affiliate': typeof AccountAffiliateRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/quotations': typeof AccountQuotationsRoute
  '/account/tax-invoices': typeof AccountTaxInvoicesRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/catalogs': typeof AdminCatalogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/credit': typeof AdminCreditRoute
  '/admin/dealers': typeof AdminDealersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/quotations': typeof AdminQuotationsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales-order': typeof AdminSalesOrderRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tiers': typeof AdminTiersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dealer/catalog': typeof DealerCatalogRoute
  '/dealer/quotations': typeof DealerQuotationsRoute
  '/dealer/wallet': typeof DealerWalletRoute
  '/_store/': typeof StoreIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dealer/': typeof DealerIndexRoute
  '/_store/catalogs/$id': typeof StoreCatalogsIdRoute
  '/_store/dealer/register': typeof StoreDealerRegisterRoute
  '/_store/products/$slug': typeof StoreProductsSlugRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/members/$userId': typeof AdminMembersUserIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/quotations/$quotationId': typeof AdminQuotationsQuotationIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/v1/admin-tax-invoice': typeof ApiV1AdminTaxInvoiceRoute
  '/api/v1/catalog-asset': typeof ApiV1CatalogAssetRoute
  '/api/v1/customer-document': typeof ApiV1CustomerDocumentRoute
  '/api/v1/hero-banner': typeof ApiV1HeroBannerRoute
  '/api/v1/payment-slip': typeof ApiV1PaymentSlipRoute
  '/api/v1/products': typeof ApiV1ProductsRoute
  '/api/v1/profile-avatar': typeof ApiV1ProfileAvatarRoute
  '/api/v1/wallet-topup-slip': typeof ApiV1WalletTopupSlipRoute
  '/_store/catalogs/': typeof StoreCatalogsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/dealer'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/about'
    | '/cart'
    | '/catalogs'
    | '/checkout'
    | '/compare'
    | '/configurator'
    | '/contact'
    | '/cookies'
    | '/error'
    | '/privacy'
    | '/quick-order'
    | '/shop'
    | '/terms'
    | '/account/affiliate'
    | '/account/notifications'
    | '/account/orders'
    | '/account/quotations'
    | '/account/tax-invoices'
    | '/account/wishlist'
    | '/admin/banners'
    | '/admin/catalogs'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/credit'
    | '/admin/dealers'
    | '/admin/inventory'
    | '/admin/members'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/quotations'
    | '/admin/reports'
    | '/admin/sales-order'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/tiers'
    | '/admin/wallet'
    | '/auth/callback'
    | '/dealer/catalog'
    | '/dealer/quotations'
    | '/dealer/wallet'
    | '/account/'
    | '/admin/'
    | '/dealer/'
    | '/catalogs/$id'
    | '/dealer/register'
    | '/products/$slug'
    | '/account/orders/$orderId'
    | '/admin/members/$userId'
    | '/admin/orders/$orderId'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/quotations/$quotationId'
    | '/api/public/health'
    | '/api/v1/admin-tax-invoice'
    | '/api/v1/catalog-asset'
    | '/api/v1/customer-document'
    | '/api/v1/hero-banner'
    | '/api/v1/payment-slip'
    | '/api/v1/products'
    | '/api/v1/profile-avatar'
    | '/api/v1/wallet-topup-slip'
    | '/catalogs/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/configurator'
    | '/contact'
    | '/cookies'
    | '/error'
    | '/privacy'
    | '/quick-order'
    | '/shop'
    | '/terms'
    | '/account/affiliate'
    | '/account/notifications'
    | '/account/orders'
    | '/account/quotations'
    | '/account/tax-invoices'
    | '/account/wishlist'
    | '/admin/banners'
    | '/admin/catalogs'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/credit'
    | '/admin/dealers'
    | '/admin/inventory'
    | '/admin/members'
    | '/admin/orders'
    | '/admin/quotations'
    | '/admin/reports'
    | '/admin/sales-order'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/tiers'
    | '/admin/wallet'
    | '/auth/callback'
    | '/dealer/catalog'
    | '/dealer/quotations'
    | '/dealer/wallet'
    | '/'
    | '/account'
    | '/admin'
    | '/dealer'
    | '/catalogs/$id'
    | '/dealer/register'
    | '/products/$slug'
    | '/account/orders/$orderId'
    | '/admin/members/$userId'
    | '/admin/orders/$orderId'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/quotations/$quotationId'
    | '/api/public/health'
    | '/api/v1/admin-tax-invoice'
    | '/api/v1/catalog-asset'
    | '/api/v1/customer-document'
    | '/api/v1/hero-banner'
    | '/api/v1/payment-slip'
    | '/api/v1/products'
    | '/api/v1/profile-avatar'
    | '/api/v1/wallet-topup-slip'
    | '/catalogs'
    | '/admin/products'
  id:
    | '__root__'
    | '/_store'
    | '/account'
    | '/admin'
    | '/dealer'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/_store/about'
    | '/_store/cart'
    | '/_store/catalogs'
    | '/_store/checkout'
    | '/_store/compare'
    | '/_store/configurator'
    | '/_store/contact'
    | '/_store/cookies'
    | '/_store/error'
    | '/_store/privacy'
    | '/_store/quick-order'
    | '/_store/shop'
    | '/_store/terms'
    | '/account/affiliate'
    | '/account/notifications'
    | '/account/orders'
    | '/account/quotations'
    | '/account/tax-invoices'
    | '/account/wishlist'
    | '/admin/banners'
    | '/admin/catalogs'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/credit'
    | '/admin/dealers'
    | '/admin/inventory'
    | '/admin/members'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/quotations'
    | '/admin/reports'
    | '/admin/sales-order'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/tiers'
    | '/admin/wallet'
    | '/auth/callback'
    | '/dealer/catalog'
    | '/dealer/quotations'
    | '/dealer/wallet'
    | '/_store/'
    | '/account/'
    | '/admin/'
    | '/dealer/'
    | '/_store/catalogs/$id'
    | '/_store/dealer/register'
    | '/_store/products/$slug'
    | '/account/orders/$orderId'
    | '/admin/members/$userId'
    | '/admin/orders/$orderId'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/quotations/$quotationId'
    | '/api/public/health'
    | '/api/v1/admin-tax-invoice'
    | '/api/v1/catalog-asset'
    | '/api/v1/customer-document'
    | '/api/v1/hero-banner'
    | '/api/v1/payment-slip'
    | '/api/v1/products'
    | '/api/v1/profile-avatar'
    | '/api/v1/wallet-topup-slip'
    | '/_store/catalogs/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRoute: typeof StoreRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DealerRoute: typeof DealerRouteWithChildren
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiV1AdminTaxInvoiceRoute: typeof ApiV1AdminTaxInvoiceRoute
  ApiV1CatalogAssetRoute: typeof ApiV1CatalogAssetRoute
  ApiV1CustomerDocumentRoute: typeof ApiV1CustomerDocumentRoute
  ApiV1HeroBannerRoute: typeof ApiV1HeroBannerRoute
  ApiV1PaymentSlipRoute: typeof ApiV1PaymentSlipRoute
  ApiV1ProductsRoute: typeof ApiV1ProductsRoute
  ApiV1ProfileAvatarRoute: typeof ApiV1ProfileAvatarRoute
  ApiV1WalletTopupSlipRoute: typeof ApiV1WalletTopupSlipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer': {
      id: '/dealer'
      path: '/dealer'
      fullPath: '/dealer'
      preLoaderRoute: typeof DealerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/': {
      id: '/dealer/'
      path: '/'
      fullPath: '/dealer/'
      preLoaderRoute: typeof DealerIndexRouteImport
      parentRoute: typeof DealerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/dealer/wallet': {
      id: '/dealer/wallet'
      path: '/wallet'
      fullPath: '/dealer/wallet'
      preLoaderRoute: typeof DealerWalletRouteImport
      parentRoute: typeof DealerRoute
    }
    '/dealer/quotations': {
      id: '/dealer/quotations'
      path: '/quotations'
      fullPath: '/dealer/quotations'
      preLoaderRoute: typeof DealerQuotationsRouteImport
      parentRoute: typeof DealerRoute
    }
    '/dealer/catalog': {
      id: '/dealer/catalog'
      path: '/catalog'
      fullPath: '/dealer/catalog'
      preLoaderRoute: typeof DealerCatalogRouteImport
      parentRoute: typeof DealerRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tiers': {
      id: '/admin/tiers'
      path: '/tiers'
      fullPath: '/admin/tiers'
      preLoaderRoute: typeof AdminTiersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales-order': {
      id: '/admin/sales-order'
      path: '/sales-order'
      fullPath: '/admin/sales-order'
      preLoaderRoute: typeof AdminSalesOrderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotations': {
      id: '/admin/quotations'
      path: '/quotations'
      fullPath: '/admin/quotations'
      preLoaderRoute: typeof AdminQuotationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dealers': {
      id: '/admin/dealers'
      path: '/dealers'
      fullPath: '/admin/dealers'
      preLoaderRoute: typeof AdminDealersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/credit': {
      id: '/admin/credit'
      path: '/credit'
      fullPath: '/admin/credit'
      preLoaderRoute: typeof AdminCreditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogs': {
      id: '/admin/catalogs'
      path: '/catalogs'
      fullPath: '/admin/catalogs'
      preLoaderRoute: typeof AdminCatalogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/tax-invoices': {
      id: '/account/tax-invoices'
      path: '/tax-invoices'
      fullPath: '/account/tax-invoices'
      preLoaderRoute: typeof AccountTaxInvoicesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/quotations': {
      id: '/account/quotations'
      path: '/quotations'
      fullPath: '/account/quotations'
      preLoaderRoute: typeof AccountQuotationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/affiliate': {
      id: '/account/affiliate'
      path: '/affiliate'
      fullPath: '/account/affiliate'
      preLoaderRoute: typeof AccountAffiliateRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_store/terms': {
      id: '/_store/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof StoreTermsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/shop': {
      id: '/_store/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof StoreShopRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/quick-order': {
      id: '/_store/quick-order'
      path: '/quick-order'
      fullPath: '/quick-order'
      preLoaderRoute: typeof StoreQuickOrderRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/privacy': {
      id: '/_store/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof StorePrivacyRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/error': {
      id: '/_store/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof StoreErrorRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/cookies': {
      id: '/_store/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof StoreCookiesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/contact': {
      id: '/_store/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof StoreContactRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/configurator': {
      id: '/_store/configurator'
      path: '/configurator'
      fullPath: '/configurator'
      preLoaderRoute: typeof StoreConfiguratorRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/compare': {
      id: '/_store/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof StoreCompareRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout': {
      id: '/_store/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/catalogs': {
      id: '/_store/catalogs'
      path: '/catalogs'
      fullPath: '/catalogs'
      preLoaderRoute: typeof StoreCatalogsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/cart': {
      id: '/_store/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/about': {
      id: '/_store/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof StoreAboutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/_store/catalogs/': {
      id: '/_store/catalogs/'
      path: '/'
      fullPath: '/catalogs/'
      preLoaderRoute: typeof StoreCatalogsIndexRouteImport
      parentRoute: typeof StoreCatalogsRoute
    }
    '/api/v1/wallet-topup-slip': {
      id: '/api/v1/wallet-topup-slip'
      path: '/api/v1/wallet-topup-slip'
      fullPath: '/api/v1/wallet-topup-slip'
      preLoaderRoute: typeof ApiV1WalletTopupSlipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/profile-avatar': {
      id: '/api/v1/profile-avatar'
      path: '/api/v1/profile-avatar'
      fullPath: '/api/v1/profile-avatar'
      preLoaderRoute: typeof ApiV1ProfileAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/products': {
      id: '/api/v1/products'
      path: '/api/v1/products'
      fullPath: '/api/v1/products'
      preLoaderRoute: typeof ApiV1ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/payment-slip': {
      id: '/api/v1/payment-slip'
      path: '/api/v1/payment-slip'
      fullPath: '/api/v1/payment-slip'
      preLoaderRoute: typeof ApiV1PaymentSlipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/hero-banner': {
      id: '/api/v1/hero-banner'
      path: '/api/v1/hero-banner'
      fullPath: '/api/v1/hero-banner'
      preLoaderRoute: typeof ApiV1HeroBannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/customer-document': {
      id: '/api/v1/customer-document'
      path: '/api/v1/customer-document'
      fullPath: '/api/v1/customer-document'
      preLoaderRoute: typeof ApiV1CustomerDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/catalog-asset': {
      id: '/api/v1/catalog-asset'
      path: '/api/v1/catalog-asset'
      fullPath: '/api/v1/catalog-asset'
      preLoaderRoute: typeof ApiV1CatalogAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin-tax-invoice': {
      id: '/api/v1/admin-tax-invoice'
      path: '/api/v1/admin-tax-invoice'
      fullPath: '/api/v1/admin-tax-invoice'
      preLoaderRoute: typeof ApiV1AdminTaxInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quotations/$quotationId': {
      id: '/admin/quotations/$quotationId'
      path: '/$quotationId'
      fullPath: '/admin/quotations/$quotationId'
      preLoaderRoute: typeof AdminQuotationsQuotationIdRouteImport
      parentRoute: typeof AdminQuotationsRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/members/$userId': {
      id: '/admin/members/$userId'
      path: '/$userId'
      fullPath: '/admin/members/$userId'
      preLoaderRoute: typeof AdminMembersUserIdRouteImport
      parentRoute: typeof AdminMembersRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/_store/products/$slug': {
      id: '/_store/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof StoreProductsSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/dealer/register': {
      id: '/_store/dealer/register'
      path: '/dealer/register'
      fullPath: '/dealer/register'
      preLoaderRoute: typeof StoreDealerRegisterRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/catalogs/$id': {
      id: '/_store/catalogs/$id'
      path: '/$id'
      fullPath: '/catalogs/$id'
      preLoaderRoute: typeof StoreCatalogsIdRouteImport
      parentRoute: typeof StoreCatalogsRoute
    }
  }
}

interface StoreCatalogsRouteChildren {
  StoreCatalogsIdRoute: typeof StoreCatalogsIdRoute
  StoreCatalogsIndexRoute: typeof StoreCatalogsIndexRoute
}

const StoreCatalogsRouteChildren: StoreCatalogsRouteChildren = {
  StoreCatalogsIdRoute: StoreCatalogsIdRoute,
  StoreCatalogsIndexRoute: StoreCatalogsIndexRoute,
}

const StoreCatalogsRouteWithChildren = StoreCatalogsRoute._addFileChildren(
  StoreCatalogsRouteChildren,
)

interface StoreRouteChildren {
  StoreAboutRoute: typeof StoreAboutRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreCatalogsRoute: typeof StoreCatalogsRouteWithChildren
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreCompareRoute: typeof StoreCompareRoute
  StoreConfiguratorRoute: typeof StoreConfiguratorRoute
  StoreContactRoute: typeof StoreContactRoute
  StoreCookiesRoute: typeof StoreCookiesRoute
  StoreErrorRoute: typeof StoreErrorRoute
  StorePrivacyRoute: typeof StorePrivacyRoute
  StoreQuickOrderRoute: typeof StoreQuickOrderRoute
  StoreShopRoute: typeof StoreShopRoute
  StoreTermsRoute: typeof StoreTermsRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreDealerRegisterRoute: typeof StoreDealerRegisterRoute
  StoreProductsSlugRoute: typeof StoreProductsSlugRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAboutRoute: StoreAboutRoute,
  StoreCartRoute: StoreCartRoute,
  StoreCatalogsRoute: StoreCatalogsRouteWithChildren,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreCompareRoute: StoreCompareRoute,
  StoreConfiguratorRoute: StoreConfiguratorRoute,
  StoreContactRoute: StoreContactRoute,
  StoreCookiesRoute: StoreCookiesRoute,
  StoreErrorRoute: StoreErrorRoute,
  StorePrivacyRoute: StorePrivacyRoute,
  StoreQuickOrderRoute: StoreQuickOrderRoute,
  StoreShopRoute: StoreShopRoute,
  StoreTermsRoute: StoreTermsRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreDealerRegisterRoute: StoreDealerRegisterRoute,
  StoreProductsSlugRoute: StoreProductsSlugRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface AccountOrdersRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountAffiliateRoute: typeof AccountAffiliateRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountQuotationsRoute: typeof AccountQuotationsRoute
  AccountTaxInvoicesRoute: typeof AccountTaxInvoicesRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAffiliateRoute: AccountAffiliateRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountQuotationsRoute: AccountQuotationsRoute,
  AccountTaxInvoicesRoute: AccountTaxInvoicesRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminMembersRouteChildren {
  AdminMembersUserIdRoute: typeof AdminMembersUserIdRoute
}

const AdminMembersRouteChildren: AdminMembersRouteChildren = {
  AdminMembersUserIdRoute: AdminMembersUserIdRoute,
}

const AdminMembersRouteWithChildren = AdminMembersRoute._addFileChildren(
  AdminMembersRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminQuotationsRouteChildren {
  AdminQuotationsQuotationIdRoute: typeof AdminQuotationsQuotationIdRoute
}

const AdminQuotationsRouteChildren: AdminQuotationsRouteChildren = {
  AdminQuotationsQuotationIdRoute: AdminQuotationsQuotationIdRoute,
}

const AdminQuotationsRouteWithChildren = AdminQuotationsRoute._addFileChildren(
  AdminQuotationsRouteChildren,
)

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCatalogsRoute: typeof AdminCatalogsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCreditRoute: typeof AdminCreditRoute
  AdminDealersRoute: typeof AdminDealersRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMembersRoute: typeof AdminMembersRouteWithChildren
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminQuotationsRoute: typeof AdminQuotationsRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSalesOrderRoute: typeof AdminSalesOrderRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTiersRoute: typeof AdminTiersRoute
  AdminWalletRoute: typeof AdminWalletRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCatalogsRoute: AdminCatalogsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCreditRoute: AdminCreditRoute,
  AdminDealersRoute: AdminDealersRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMembersRoute: AdminMembersRouteWithChildren,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminQuotationsRoute: AdminQuotationsRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  AdminSalesOrderRoute: AdminSalesOrderRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTiersRoute: AdminTiersRoute,
  AdminWalletRoute: AdminWalletRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DealerRouteChildren {
  DealerCatalogRoute: typeof DealerCatalogRoute
  DealerQuotationsRoute: typeof DealerQuotationsRoute
  DealerWalletRoute: typeof DealerWalletRoute
  DealerIndexRoute: typeof DealerIndexRoute
}

const DealerRouteChildren: DealerRouteChildren = {
  DealerCatalogRoute: DealerCatalogRoute,
  DealerQuotationsRoute: DealerQuotationsRoute,
  DealerWalletRoute: DealerWalletRoute,
  DealerIndexRoute: DealerIndexRoute,
}

const DealerRouteWithChildren =
  DealerRoute._addFileChildren(DealerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StoreRoute: StoreRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DealerRoute: DealerRouteWithChildren,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiV1AdminTaxInvoiceRoute: ApiV1AdminTaxInvoiceRoute,
  ApiV1CatalogAssetRoute: ApiV1CatalogAssetRoute,
  ApiV1CustomerDocumentRoute: ApiV1CustomerDocumentRoute,
  ApiV1HeroBannerRoute: ApiV1HeroBannerRoute,
  ApiV1PaymentSlipRoute: ApiV1PaymentSlipRoute,
  ApiV1ProductsRoute: ApiV1ProductsRoute,
  ApiV1ProfileAvatarRoute: ApiV1ProfileAvatarRoute,
  ApiV1WalletTopupSlipRoute: ApiV1WalletTopupSlipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
