/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DealerRouteImport } from './routes/dealer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as DealerIndexRouteImport } from './routes/dealer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as StoreIndexRouteImport } from './routes/_store.index'
import { Route as DealerWalletRouteImport } from './routes/dealer.wallet'
import { Route as DealerQuotationsRouteImport } from './routes/dealer.quotations'
import { Route as DealerCatalogRouteImport } from './routes/dealer.catalog'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminTiersRouteImport } from './routes/admin.tiers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSalesOrderRouteImport } from './routes/admin.sales-order'
import { Route as AdminQuotationsRouteImport } from './routes/admin.quotations'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminDealersRouteImport } from './routes/admin.dealers'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AccountTrackRouteImport } from './routes/account.track'
import { Route as AccountQuotationsRouteImport } from './routes/account.quotations'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as StoreShopRouteImport } from './routes/_store.shop'
import { Route as StoreErrorRouteImport } from './routes/_store.error'
import { Route as StoreContactRouteImport } from './routes/_store.contact'
import { Route as StoreConfiguratorRouteImport } from './routes/_store.configurator'
import { Route as StoreCheckoutRouteImport } from './routes/_store.checkout'
import { Route as StoreCartRouteImport } from './routes/_store.cart'
import { Route as StoreAboutRouteImport } from './routes/_store.about'
import { Route as ApiV1WalletTopupSlipRouteImport } from './routes/api/v1/wallet-topup-slip'
import { Route as ApiV1ProductsRouteImport } from './routes/api/v1/products'
import { Route as ApiV1PaymentSlipRouteImport } from './routes/api/v1/payment-slip'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'
import { Route as StoreProductsSlugRouteImport } from './routes/_store.products.$slug'
import { Route as StoreDealerRegisterRouteImport } from './routes/_store.dealer.register'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerRoute = DealerRouteImport.update({
  id: '/dealer',
  path: '/dealer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerIndexRoute = DealerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DealerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const DealerWalletRoute = DealerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DealerRoute,
} as any)
const DealerQuotationsRoute = DealerQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => DealerRoute,
} as any)
const DealerCatalogRoute = DealerCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => DealerRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTiersRoute = AdminTiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesOrderRoute = AdminSalesOrderRouteImport.update({
  id: '/sales-order',
  path: '/sales-order',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotationsRoute = AdminQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealersRoute = AdminDealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AccountTrackRoute = AccountTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => AccountRoute,
} as any)
const AccountQuotationsRoute = AccountQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const StoreShopRoute = StoreShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StoreRoute,
} as any)
const StoreErrorRoute = StoreErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContactRoute = StoreContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => StoreRoute,
} as any)
const StoreConfiguratorRoute = StoreConfiguratorRouteImport.update({
  id: '/configurator',
  path: '/configurator',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAboutRoute = StoreAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => StoreRoute,
} as any)
const ApiV1WalletTopupSlipRoute = ApiV1WalletTopupSlipRouteImport.update({
  id: '/api/v1/wallet-topup-slip',
  path: '/api/v1/wallet-topup-slip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProductsRoute = ApiV1ProductsRouteImport.update({
  id: '/api/v1/products',
  path: '/api/v1/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PaymentSlipRoute = ApiV1PaymentSlipRouteImport.update({
  id: '/api/v1/payment-slip',
  path: '/api/v1/payment-slip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const StoreProductsSlugRoute = StoreProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreDealerRegisterRoute = StoreDealerRegisterRouteImport.update({
  id: '/dealer/register',
  path: '/dealer/register',
  getParentRoute: () => StoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dealer': typeof DealerRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about': typeof StoreAboutRoute
  '/cart': typeof StoreCartRoute
  '/checkout': typeof StoreCheckoutRoute
  '/configurator': typeof StoreConfiguratorRoute
  '/contact': typeof StoreContactRoute
  '/error': typeof StoreErrorRoute
  '/shop': typeof StoreShopRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/quotations': typeof AccountQuotationsRoute
  '/account/track': typeof AccountTrackRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dealers': typeof AdminDealersRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/quotations': typeof AdminQuotationsRoute
  '/admin/sales-order': typeof AdminSalesOrderRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tiers': typeof AdminTiersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dealer/catalog': typeof DealerCatalogRoute
  '/dealer/quotations': typeof DealerQuotationsRoute
  '/dealer/wallet': typeof DealerWalletRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dealer/': typeof DealerIndexRoute
  '/dealer/register': typeof StoreDealerRegisterRoute
  '/products/$slug': typeof StoreProductsSlugRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/v1/payment-slip': typeof ApiV1PaymentSlipRoute
  '/api/v1/products': typeof ApiV1ProductsRoute
  '/api/v1/wallet-topup-slip': typeof ApiV1WalletTopupSlipRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about': typeof StoreAboutRoute
  '/cart': typeof StoreCartRoute
  '/checkout': typeof StoreCheckoutRoute
  '/configurator': typeof StoreConfiguratorRoute
  '/contact': typeof StoreContactRoute
  '/error': typeof StoreErrorRoute
  '/shop': typeof StoreShopRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/quotations': typeof AccountQuotationsRoute
  '/account/track': typeof AccountTrackRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dealers': typeof AdminDealersRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/quotations': typeof AdminQuotationsRoute
  '/admin/sales-order': typeof AdminSalesOrderRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tiers': typeof AdminTiersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dealer/catalog': typeof DealerCatalogRoute
  '/dealer/quotations': typeof DealerQuotationsRoute
  '/dealer/wallet': typeof DealerWalletRoute
  '/': typeof StoreIndexRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/dealer': typeof DealerIndexRoute
  '/dealer/register': typeof StoreDealerRegisterRoute
  '/products/$slug': typeof StoreProductsSlugRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/v1/payment-slip': typeof ApiV1PaymentSlipRoute
  '/api/v1/products': typeof ApiV1ProductsRoute
  '/api/v1/wallet-topup-slip': typeof ApiV1WalletTopupSlipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dealer': typeof DealerRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_store/about': typeof StoreAboutRoute
  '/_store/cart': typeof StoreCartRoute
  '/_store/checkout': typeof StoreCheckoutRoute
  '/_store/configurator': typeof StoreConfiguratorRoute
  '/_store/contact': typeof StoreContactRoute
  '/_store/error': typeof StoreErrorRoute
  '/_store/shop': typeof StoreShopRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/quotations': typeof AccountQuotationsRoute
  '/account/track': typeof AccountTrackRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dealers': typeof AdminDealersRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/quotations': typeof AdminQuotationsRoute
  '/admin/sales-order': typeof AdminSalesOrderRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tiers': typeof AdminTiersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dealer/catalog': typeof DealerCatalogRoute
  '/dealer/quotations': typeof DealerQuotationsRoute
  '/dealer/wallet': typeof DealerWalletRoute
  '/_store/': typeof StoreIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dealer/': typeof DealerIndexRoute
  '/_store/dealer/register': typeof StoreDealerRegisterRoute
  '/_store/products/$slug': typeof StoreProductsSlugRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/v1/payment-slip': typeof ApiV1PaymentSlipRoute
  '/api/v1/products': typeof ApiV1ProductsRoute
  '/api/v1/wallet-topup-slip': typeof ApiV1WalletTopupSlipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/dealer'
    | '/login'
    | '/signup'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/configurator'
    | '/contact'
    | '/error'
    | '/shop'
    | '/account/notifications'
    | '/account/orders'
    | '/account/quotations'
    | '/account/track'
    | '/admin/categories'
    | '/admin/dealers'
    | '/admin/members'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/quotations'
    | '/admin/sales-order'
    | '/admin/settings'
    | '/admin/tiers'
    | '/admin/wallet'
    | '/auth/callback'
    | '/dealer/catalog'
    | '/dealer/quotations'
    | '/dealer/wallet'
    | '/account/'
    | '/admin/'
    | '/dealer/'
    | '/dealer/register'
    | '/products/$slug'
    | '/account/orders/$orderId'
    | '/admin/orders/$orderId'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/api/public/health'
    | '/api/v1/payment-slip'
    | '/api/v1/products'
    | '/api/v1/wallet-topup-slip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/configurator'
    | '/contact'
    | '/error'
    | '/shop'
    | '/account/notifications'
    | '/account/orders'
    | '/account/quotations'
    | '/account/track'
    | '/admin/categories'
    | '/admin/dealers'
    | '/admin/members'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/quotations'
    | '/admin/sales-order'
    | '/admin/settings'
    | '/admin/tiers'
    | '/admin/wallet'
    | '/auth/callback'
    | '/dealer/catalog'
    | '/dealer/quotations'
    | '/dealer/wallet'
    | '/'
    | '/account'
    | '/admin'
    | '/dealer'
    | '/dealer/register'
    | '/products/$slug'
    | '/account/orders/$orderId'
    | '/admin/orders/$orderId'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/api/public/health'
    | '/api/v1/payment-slip'
    | '/api/v1/products'
    | '/api/v1/wallet-topup-slip'
  id:
    | '__root__'
    | '/_store'
    | '/account'
    | '/admin'
    | '/dealer'
    | '/login'
    | '/signup'
    | '/_store/about'
    | '/_store/cart'
    | '/_store/checkout'
    | '/_store/configurator'
    | '/_store/contact'
    | '/_store/error'
    | '/_store/shop'
    | '/account/notifications'
    | '/account/orders'
    | '/account/quotations'
    | '/account/track'
    | '/admin/categories'
    | '/admin/dealers'
    | '/admin/members'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/quotations'
    | '/admin/sales-order'
    | '/admin/settings'
    | '/admin/tiers'
    | '/admin/wallet'
    | '/auth/callback'
    | '/dealer/catalog'
    | '/dealer/quotations'
    | '/dealer/wallet'
    | '/_store/'
    | '/account/'
    | '/admin/'
    | '/dealer/'
    | '/_store/dealer/register'
    | '/_store/products/$slug'
    | '/account/orders/$orderId'
    | '/admin/orders/$orderId'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/api/public/health'
    | '/api/v1/payment-slip'
    | '/api/v1/products'
    | '/api/v1/wallet-topup-slip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRoute: typeof StoreRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DealerRoute: typeof DealerRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiV1PaymentSlipRoute: typeof ApiV1PaymentSlipRoute
  ApiV1ProductsRoute: typeof ApiV1ProductsRoute
  ApiV1WalletTopupSlipRoute: typeof ApiV1WalletTopupSlipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer': {
      id: '/dealer'
      path: '/dealer'
      fullPath: '/dealer'
      preLoaderRoute: typeof DealerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/': {
      id: '/dealer/'
      path: '/'
      fullPath: '/dealer/'
      preLoaderRoute: typeof DealerIndexRouteImport
      parentRoute: typeof DealerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/dealer/wallet': {
      id: '/dealer/wallet'
      path: '/wallet'
      fullPath: '/dealer/wallet'
      preLoaderRoute: typeof DealerWalletRouteImport
      parentRoute: typeof DealerRoute
    }
    '/dealer/quotations': {
      id: '/dealer/quotations'
      path: '/quotations'
      fullPath: '/dealer/quotations'
      preLoaderRoute: typeof DealerQuotationsRouteImport
      parentRoute: typeof DealerRoute
    }
    '/dealer/catalog': {
      id: '/dealer/catalog'
      path: '/catalog'
      fullPath: '/dealer/catalog'
      preLoaderRoute: typeof DealerCatalogRouteImport
      parentRoute: typeof DealerRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tiers': {
      id: '/admin/tiers'
      path: '/tiers'
      fullPath: '/admin/tiers'
      preLoaderRoute: typeof AdminTiersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales-order': {
      id: '/admin/sales-order'
      path: '/sales-order'
      fullPath: '/admin/sales-order'
      preLoaderRoute: typeof AdminSalesOrderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotations': {
      id: '/admin/quotations'
      path: '/quotations'
      fullPath: '/admin/quotations'
      preLoaderRoute: typeof AdminQuotationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dealers': {
      id: '/admin/dealers'
      path: '/dealers'
      fullPath: '/admin/dealers'
      preLoaderRoute: typeof AdminDealersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/track': {
      id: '/account/track'
      path: '/track'
      fullPath: '/account/track'
      preLoaderRoute: typeof AccountTrackRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/quotations': {
      id: '/account/quotations'
      path: '/quotations'
      fullPath: '/account/quotations'
      preLoaderRoute: typeof AccountQuotationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_store/shop': {
      id: '/_store/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof StoreShopRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/error': {
      id: '/_store/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof StoreErrorRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/contact': {
      id: '/_store/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof StoreContactRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/configurator': {
      id: '/_store/configurator'
      path: '/configurator'
      fullPath: '/configurator'
      preLoaderRoute: typeof StoreConfiguratorRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout': {
      id: '/_store/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/cart': {
      id: '/_store/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/about': {
      id: '/_store/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof StoreAboutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/api/v1/wallet-topup-slip': {
      id: '/api/v1/wallet-topup-slip'
      path: '/api/v1/wallet-topup-slip'
      fullPath: '/api/v1/wallet-topup-slip'
      preLoaderRoute: typeof ApiV1WalletTopupSlipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/products': {
      id: '/api/v1/products'
      path: '/api/v1/products'
      fullPath: '/api/v1/products'
      preLoaderRoute: typeof ApiV1ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/payment-slip': {
      id: '/api/v1/payment-slip'
      path: '/api/v1/payment-slip'
      fullPath: '/api/v1/payment-slip'
      preLoaderRoute: typeof ApiV1PaymentSlipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/_store/products/$slug': {
      id: '/_store/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof StoreProductsSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/dealer/register': {
      id: '/_store/dealer/register'
      path: '/dealer/register'
      fullPath: '/dealer/register'
      preLoaderRoute: typeof StoreDealerRegisterRouteImport
      parentRoute: typeof StoreRoute
    }
  }
}

interface StoreRouteChildren {
  StoreAboutRoute: typeof StoreAboutRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreConfiguratorRoute: typeof StoreConfiguratorRoute
  StoreContactRoute: typeof StoreContactRoute
  StoreErrorRoute: typeof StoreErrorRoute
  StoreShopRoute: typeof StoreShopRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreDealerRegisterRoute: typeof StoreDealerRegisterRoute
  StoreProductsSlugRoute: typeof StoreProductsSlugRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAboutRoute: StoreAboutRoute,
  StoreCartRoute: StoreCartRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreConfiguratorRoute: StoreConfiguratorRoute,
  StoreContactRoute: StoreContactRoute,
  StoreErrorRoute: StoreErrorRoute,
  StoreShopRoute: StoreShopRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreDealerRegisterRoute: StoreDealerRegisterRoute,
  StoreProductsSlugRoute: StoreProductsSlugRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface AccountOrdersRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountQuotationsRoute: typeof AccountQuotationsRoute
  AccountTrackRoute: typeof AccountTrackRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountQuotationsRoute: AccountQuotationsRoute,
  AccountTrackRoute: AccountTrackRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminOrdersRouteChildren {
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDealersRoute: typeof AdminDealersRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminQuotationsRoute: typeof AdminQuotationsRoute
  AdminSalesOrderRoute: typeof AdminSalesOrderRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTiersRoute: typeof AdminTiersRoute
  AdminWalletRoute: typeof AdminWalletRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDealersRoute: AdminDealersRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminQuotationsRoute: AdminQuotationsRoute,
  AdminSalesOrderRoute: AdminSalesOrderRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTiersRoute: AdminTiersRoute,
  AdminWalletRoute: AdminWalletRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DealerRouteChildren {
  DealerCatalogRoute: typeof DealerCatalogRoute
  DealerQuotationsRoute: typeof DealerQuotationsRoute
  DealerWalletRoute: typeof DealerWalletRoute
  DealerIndexRoute: typeof DealerIndexRoute
}

const DealerRouteChildren: DealerRouteChildren = {
  DealerCatalogRoute: DealerCatalogRoute,
  DealerQuotationsRoute: DealerQuotationsRoute,
  DealerWalletRoute: DealerWalletRoute,
  DealerIndexRoute: DealerIndexRoute,
}

const DealerRouteWithChildren =
  DealerRoute._addFileChildren(DealerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StoreRoute: StoreRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DealerRoute: DealerRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiV1PaymentSlipRoute: ApiV1PaymentSlipRoute,
  ApiV1ProductsRoute: ApiV1ProductsRoute,
  ApiV1WalletTopupSlipRoute: ApiV1WalletTopupSlipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
